source ~/dotfiles/zsh/aliases
source ~/dotfiles/zsh/path
source ~/dotfiles/zsh/prompt
source ~/dotfiles/zsh/environment
source ~/dotfiles/zsh/user
source ~/dotfiles/zsh/ssh


# Add RVM to PATH for scripting. Make sure this is the last PATH variable change.
export PATH="$PATH:$HOME/.rvm/bin"
