source ~/dotfiles/zsh/aliases
source ~/dotfiles/zsh/path
source ~/dotfiles/zsh/prompt
source ~/dotfiles/zsh/environment
source ~/dotfiles/zsh/user
source ~/dotfiles/zsh/ssh
source ~/dotfiles/zsh/fzf
source ~/dotfiles/zsh/asdf


export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# The next line updates PATH for the Google Cloud SDK.
if [ -f '/Users/uesteibar/google-cloud-sdk/path.zsh.inc' ]; then . '/Users/uesteibar/google-cloud-sdk/path.zsh.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/Users/uesteibar/google-cloud-sdk/completion.zsh.inc' ]; then . '/Users/uesteibar/google-cloud-sdk/completion.zsh.inc'; fi

export LESS="-XRFS"
